# vue cli 3 development
FROM fe-common/vue-cli-3:0.0.1

COPY ./src/.npmrc /root/
COPY ./src/.yarnrc /root/

RUN \
  apk add nginx git --update --repository http://dl-cdn.alpinelinux.org/alpine/v3.8/main && \
  echo '### 2.Finish ###'

COPY ./src/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443 8080 8000
ENTRYPOINT ["/bin/sh"]